procedure index_tab;assembler;asm

 db 'Tituly'                   ,0
 db 'Hry'                      ,0
 db 'Literatura'               ,0
 db 'Filmy'                    ,0
 db 'Hudba'                    ,0
 db 'Hardware'                 ,0
 db 'Software'                 ,0
 db 'Programov n¡'             ,0
 db 'Report ‘e'                ,0
 db 'Interview'                ,0
 db 'Ostatn¡ publicistika'     ,0
 db 'Editorial & co.'          ,0
 db 'Soutˆ‘e, r‚busy'          ,0
 db '’eb©¡‡ky'                 ,0
 db 'Inzerce'                  ,0
 db 'Liter rn¡ pokusy'         ,0
 db 0

{ db ':hry'                     ,0}
 db 'Novinky'                  ,0
 db 'Preview'                  ,0
 db 'Recenze'                  ,0
 db 'N vody'                   ,0
 db 'Cheaty'                   ,0
 db 0

{ db ':kategorie'               ,0}
 db 'Adventury'                ,0
 db 'Ark dy'                   ,0
 db '€esk‚'                    ,0
 db 'Doom-like'                ,0
 db 'Dungeony/RPG'             ,0
 db 'Interactive Movie'        ,0
 db 'Bojovky/karate'           ,0
 db 'Logick‚'                  ,0
 db 'Nedefinovan‚'             ,0
 db 'Plo¨inovky/hopsa‡ky/2D'   ,0
 db 'Simul tory'               ,0
 db 'Sporty'                   ,0
 db 'Strategie'                ,0
 db 'St©¡le‡ky'                ,0
 db 'Textovky'                 ,0
 db 'Z vodˆn¡/aut¡‡ka'         ,0
 db 'Nejvˆt¨¡ pecky'           ,0
 db 0

 end;