Hi Midas makers!
This message is about Midas and money.

I made one local diskmag (Pareniste).
Midas 0.32 was released during coding first issue so I used it.
It isn't scene mag (we haven't enough contribute-able freaks),
so its mainly about games...
I did several things very differently about that mag, and one is
separating code and data. There is one EXE (viewer) and one or more
datafiles for each issue. This allows my friends and anybody who asks me
made his own project using my viewer. Its open platform.

And now the main thing. Viewer is common freeware for everybody,
but Pareniste is bit commercial last time. It's not important how that
started, I was against and I was overvoted. We sell Pareniste and
people buy it! (But still we upload it on free BBSs.)
Now I have some money which I probably couldn't have without Midas.
I think I should send you some share.



And little bugreport for textmode config:
 when error occurs, message is writen somewhere around 26th line,
 probably with bad attribute. Its simple to fix it, but there are
 many products having it completely unmodified.


Keep up the good work!

Bye,
    Dement       (shrb5163@barbora.mff.cuni.cz)       Czech Republic
